# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta28
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - context: ../
    image: plant-service
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - ../.k8s/**
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
