// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PlantClient is the client API for Plant service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlantClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type plantClient struct {
	cc grpc.ClientConnInterface
}

func NewPlantClient(cc grpc.ClientConnInterface) PlantClient {
	return &plantClient{cc}
}

func (c *plantClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/Plant/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlantServer is the server API for Plant service.
// All implementations must embed UnimplementedPlantServer
// for forward compatibility
type PlantServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedPlantServer()
}

// UnimplementedPlantServer must be embedded to have forward compatible implementations.
type UnimplementedPlantServer struct {
}

func (UnimplementedPlantServer) Hello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedPlantServer) mustEmbedUnimplementedPlantServer() {}

// UnsafePlantServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlantServer will
// result in compilation errors.
type UnsafePlantServer interface {
	mustEmbedUnimplementedPlantServer()
}

func RegisterPlantServer(s grpc.ServiceRegistrar, srv PlantServer) {
	s.RegisterService(&Plant_ServiceDesc, srv)
}

func _Plant_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlantServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Plant/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlantServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Plant_ServiceDesc is the grpc.ServiceDesc for Plant service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Plant_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Plant",
	HandlerType: (*PlantServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Plant_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plant.proto",
}
