// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: plant.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A shelf resource.
type Plant struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Plant) Reset() {
	*x = Plant{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plant_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Plant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plant) ProtoMessage() {}

func (x *Plant) ProtoReflect() protoreflect.Message {
	mi := &file_plant_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plant.ProtoReflect.Descriptor instead.
func (*Plant) Descriptor() ([]byte, []int) {
	return file_plant_proto_rawDescGZIP(), []int{0}
}

func (x *Plant) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Plant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type NewPlantRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *NewPlantRequest) Reset() {
	*x = NewPlantRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plant_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewPlantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewPlantRequest) ProtoMessage() {}

func (x *NewPlantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plant_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewPlantRequest.ProtoReflect.Descriptor instead.
func (*NewPlantRequest) Descriptor() ([]byte, []int) {
	return file_plant_proto_rawDescGZIP(), []int{1}
}

func (x *NewPlantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetPlantRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetPlantRequest) Reset() {
	*x = GetPlantRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plant_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlantRequest) ProtoMessage() {}

func (x *GetPlantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plant_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlantRequest.ProtoReflect.Descriptor instead.
func (*GetPlantRequest) Descriptor() ([]byte, []int) {
	return file_plant_proto_rawDescGZIP(), []int{2}
}

func (x *GetPlantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_plant_proto protoreflect.FileDescriptor

var file_plant_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2b, 0x0a, 0x05, 0x50,
	0x6c, 0x61, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x25, 0x0a, 0x0f, 0x4e, 0x65, 0x77, 0x50,
	0x6c, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x25, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x88, 0x01, 0x0a, 0x06, 0x50, 0x6c, 0x61, 0x6e, 0x74,
	0x73, 0x12, 0x3f, 0x0a, 0x08, 0x4e, 0x65, 0x77, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x12, 0x10, 0x2e,
	0x4e, 0x65, 0x77, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x06, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x22,
	0x0a, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x73, 0x3a, 0x05, 0x70, 0x6c, 0x61,
	0x6e, 0x74, 0x12, 0x3d, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x12, 0x10,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x06, 0x2e, 0x50, 0x6c, 0x61, 0x6e, 0x74, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x11,
	0x12, 0x0f, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6c, 0x61, 0x6e, 0x74, 0x73, 0x2f, 0x7b, 0x69, 0x64,
	0x7d, 0x42, 0x40, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x67, 0x6c, 0x61, 0x73, 0x73, 0x67, 0x72, 0x65, 0x65, 0x6e, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x2f,
	0x70, 0x6c, 0x61, 0x6e, 0x74, 0x73, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x69,
	0x6e, 0x66, 0x72, 0x61, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_plant_proto_rawDescOnce sync.Once
	file_plant_proto_rawDescData = file_plant_proto_rawDesc
)

func file_plant_proto_rawDescGZIP() []byte {
	file_plant_proto_rawDescOnce.Do(func() {
		file_plant_proto_rawDescData = protoimpl.X.CompressGZIP(file_plant_proto_rawDescData)
	})
	return file_plant_proto_rawDescData
}

var file_plant_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_plant_proto_goTypes = []interface{}{
	(*Plant)(nil),           // 0: Plant
	(*NewPlantRequest)(nil), // 1: NewPlantRequest
	(*GetPlantRequest)(nil), // 2: GetPlantRequest
}
var file_plant_proto_depIdxs = []int32{
	1, // 0: Plants.NewPlant:input_type -> NewPlantRequest
	2, // 1: Plants.GetPlant:input_type -> GetPlantRequest
	0, // 2: Plants.NewPlant:output_type -> Plant
	0, // 3: Plants.GetPlant:output_type -> Plant
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_plant_proto_init() }
func file_plant_proto_init() {
	if File_plant_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_plant_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Plant); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plant_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewPlantRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plant_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlantRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_plant_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plant_proto_goTypes,
		DependencyIndexes: file_plant_proto_depIdxs,
		MessageInfos:      file_plant_proto_msgTypes,
	}.Build()
	File_plant_proto = out.File
	file_plant_proto_rawDesc = nil
	file_plant_proto_goTypes = nil
	file_plant_proto_depIdxs = nil
}
